### ISSUE TITLE
example cpp does not run. it says KEYimu_dt*NOT FOUND

### ISSUE THREAD

**Issue by K0stIa** [MARSLab-UMN/MARS-VINS#11]
trying to run Regular_1 dataset. It says: KEYimu_dt*NOT FOUND

**Comment by K0stIa** [comment]
solved it already. :)

**Comment by jvgomez** [comment]
@K0stIa how did you fix it? I am having the same issue.

**Comment by K0stIa** [comment]
If I remember it correctly, the problem was that I was using a wrong config file. Make sure you are using this config file. https://github.com/MARSLab-UMN/MARS-VINS/blob/master/config/sample_config.txt

**Comment by jvgomez** [comment]
Yep, that was it! Weird, because I was using the one delivered with the datasets. But thanks a lot @K0stIa
